package: public
output: ../generated/public/public.gen.go

generate:
  gorilla-server: true
  strict-server: true
  models: true

output-options:
  skip-prune: true

import-mapping:
  openapi-models.yml: github.com/alishashelby/Samok-Aah-t/backend/internal/app/api/generated/models


